spring.application.name=Department-And-Employees-System-OTM

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=root123
spring.datasource.url=jdbc:mysql:///nit710

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
