spring.application.name=Student-Details-Binding-System

#info.company.department.deptId=101
#info.company.department.deptName=HR
#info.company.department.deptId=102
#info.company.department.deptName=IT
#info.company.department.deptId=103
#info.company.department.deptName=Finance
#info.company.studentCourse=B.Tech
info.product.features=Fast , reliable, Daily Use
info.product.categories= phone,Electronic,Education
info.product.tags= phone,Electronic,Education
info.product.stock.Mobile =100
info.product.stock.Tv =98
info.product.stock.Laptop =101
info.product.supplier.name=Vishal Mega Mart
info.product.supplier.location= Front Of Bhageshree Hotel
info.product.supplier.contact=5000169090
