spring.application.name=Student-Addmission-And-Grade-Evaluation-System

server.port=8989
spring.mvc.view.prefix=/WEB-INF/pages
spring.mvc.view.suffix=.jsp

server.servlet.context-path=/StudentAddmission
