spring.application.name=Student-Details-Binding-System

#info.company.department.deptId=101
#info.company.department.deptName=HR
#info.company.department.deptId=102
#info.company.department.deptName=IT
#info.company.department.deptId=103
#info.company.department.deptName=Finance
#info.company.studentCourse=B.Tech
info.employee.skills=Java , Spring Boot , Oracle 
info.employee.projects=Employee Management, Job Portal , Electricity Bill 
info.employee.tools=VS Code, Eclipse IDE, Intellij IDE, Android Studio
info.employee.experience.Java_Developer =2
info.employee.experience.FullStack_Developer =5
info.employee.experience.Software_Developer =7
info.employee.address.city=Hyderabad
info.employee.address.state=Telanagana
info.employee.address.pincode=500016
