spring.application.name=Student-Details-Binding-System

#info.company.department.deptId=101
#info.company.department.deptName=HR
#info.company.department.deptId=102
#info.company.department.deptName=IT
#info.company.department.deptId=103
#info.company.department.deptName=Finance
#info.company.studentCourse=B.Tech
info.
info.company.departments[0].deptId=101
info.company.departments[0].deptName=HR
info.company.departments[1].deptId=102
info.company.departments[1].deptName=IT
info.company.departments[2].deptId=103
info.company.departments[2].deptName=Finance


