spring.application.name=Student-Details-Binding-System

#info.company.department.deptId=101
#info.company.department.deptName=HR
#info.company.department.deptId=102
#info.company.department.deptName=IT
#info.company.department.deptId=103
#info.company.department.deptName=Finance
#info.company.studentCourse=B.Tech

info.bank.banks.account-number=1234567890
info.bank.banks.holder-name=sushant singh
info.bank.banks.balance=555000

