spring.application.name=Student-Details-Binding-System

#info.company.department.deptId=101
#info.company.department.deptName=HR
#info.company.department.deptId=102
#info.company.department.deptName=IT
#info.company.department.deptId=103
#info.company.department.deptName=Finance
#info.company.studentCourse=B.Tech
info.employee.hobbies= Coding , Inventing Api, Full Stack Projects
info.employee.subjects=Employee Management, Job Portal , Electricity Bill 
info.employee.certifications=VS Code, Eclipse IDE, Intellij IDE, Android Studio
info.employee.marks.Java_Developer =100
info.employee.marks..FullStack_Developer =98
info.employee.marks..Software_Developer =101
info.employee.address.city=Hyderabad
info.employee.address.state=Telanagana
info.employee.address.pincode=500016
