spring.application.name=Student-Details-Binding-System

#info.company.department.deptId=101
#info.company.department.deptName=HR
#info.company.department.deptId=102
#info.company.department.deptName=IT
#info.company.department.deptId=103
#info.company.department.deptName=Finance
#info.company.studentCourse=B.Tech
info.books.books[0].name=Trading in The Zone
info.books.books[1].name=Atomic Habits
info.books.books[2].name=The Money Psychology 
info.books.books[3].name=The Alone Man
