spring.application.name=Student-Details-Binding-System

#info.company.department.deptId=101
#info.company.department.deptName=HR
#info.company.department.deptId=102
#info.company.department.deptName=IT
#info.company.department.deptId=103
#info.company.department.deptName=Finance
#info.company.studentCourse=B.Tech
info.student.students[0].id=101
info.student.students[0].name=ramesh
info.student.students[0].marks=99
info.student.students[1].id=102
info.student.students[1].name=vijay
info.student.students[1].marks=88
info.student.students[2].id=103
info.student.students[2].name=kartik
info.student.students[2].marks=98